DELIMITER ;   
DROP SCHEMA IF EXISTS XPROJECT1_DB;
CREATE DATABASE XPROJECT1_DB;
USE XPROJECT1_DB;
CREATE TABLE RIDER (
    ID_RIDER INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(10) NOT NULL,
    PASS_CODE VARCHAR(100),
    PHONE_NUMBER VARCHAR(13),
    SIGNUP_DATE DATETIME DEFAULT NOW(),
    IS_VALID BOOLEAN DEFAULT TRUE,
    UNVALADATION_DATE DATETIME
);
CREATE TABLE CARBRAND (
    ID_BRAND INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_NAME VARCHAR(100) NOT NULL
);
CREATE TABLE MODEL (
    ID_MODEL INT AUTO_INCREMENT,
    ID_BRAND INT,
    MADE_YEAR YEAR NOT NULL,
    MODEL_LABEL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_MODEL , ID_BRAND),
    FOREIGN KEY (ID_BRAND)
        REFERENCES CARBRAND (ID_BRAND)
);
CREATE TABLE RIDER_CAR (
    ID_RIDER_CAR INT UNIQUE AUTO_INCREMENT,
    ID_RIDER INT REFERENCES RIDER (ID_RIDER),
    ID_MODEL INT REFERENCES MODEL (ID_MODEL),
    DATE_ADDED DATETIME DEFAULT NOW(),
    PRIMARY KEY (ID_RIDER , ID_MODEL),
    FOREIGN KEY (ID_RIDER)
        REFERENCES RIDER (ID_RIDER),
    FOREIGN KEY (ID_MODEL)
        REFERENCES MODEL (ID_MODEL)
);
CREATE TABLE WILAYA (
    WILAYA_CODE INT PRIMARY KEY,
    WILAYA_LABEL VARCHAR(30)
);
CREATE TABLE CITY (
    ID_CITY INT AUTO_INCREMENT PRIMARY KEY,
    WILAYA_CODE INT,
    CITY_LABEL VARCHAR(70),
    FOREIGN KEY (WILAYA_CODE)
        REFERENCES WILAYA (WILAYA_CODE)
);
CREATE TABLE TRIP (
    ID_TRIP INT AUTO_INCREMENT PRIMARY KEY,
    ID_RIDER_CAR INT,
    SP_ID_CITY INT,
    EP_ID_CITY INT,
    SP_DATE_TIME DATETIME,
    CREATION_DATE DATETIME DEFAULT NOW(),
    IS_VALID BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ID_RIDER_CAR)
        REFERENCES RIDER_CAR (ID_RIDER_CAR),
    FOREIGN KEY (SP_ID_CITY)
        REFERENCES CITY (ID_CITY),
    FOREIGN KEY (EP_ID_CITY)
        REFERENCES CITY (ID_CITY),
    CHECK (SP_ID_CITY <> EP_ID_CITY)
);
